config/routes.rb
Rails.application.routes.draw do
  root 'profiles#show'

  resources :users, only: [:new, :create, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, confirmation: { case_sensitive: true }, length: { minimum: 8 }
  validate on: :update do
    validate_username_length if edit_username?
  end

  before_save :assign_username, if: -> { username.blank? }
  after_create :send_welcome_mail

  def assign_username
    self.username = email.match(/(.+)@/)[1]
  end

  def authenticate(given_password)
    given_password == password
  end

  def send_welcome_mail
    UserMailer.welcome_email(self).deliver_later
  end

  def generate_password_token!
    begin
      self.reset_password_token = SecureRandom.urlsafe_base64
    end while User.exists?(reset_password_token: self.reset_password_token)
    self.reset_password_token_expires_at = 6.hours.from_now
    save!
  end

  def clear_password_token!
    self.reset_password_token = nil
    self.reset_password_token_expires_at = nil
    save!
  end

  def validate_username_length
    return if username.length >= 5
    errors.add(:username, 'Must at least have five characters.')
  end

  def edit_username?
    username_changed?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: %i[edit update]

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:user][:email])
    if user
      user.generate_password_token!
      UserMailer.reset_password(user).deliver_later
    end
    flash[:notice] = "The reset password email is sent!"
    redirect_to root_path
  end

  def edit
    unless @user&.reset_password_token_expires_at && @user.reset_password_token_expires_at > Time.now
      flash[:alert] = 'The link is expired!'
      redirect_to root_path
    end
  end

  def update
    if @user.update(password_params)
      @user.clear_password_token!
      flash[:notice] = "The password is reset!"
      redirect_to login_path
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render 'edit'
    end
  end

  private

  def get_user
    @user = User.find_by(reset_password_token: params[:id])
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    if current_user
      @user = current_user
      render 'show'
    else
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "You are successfully logged in!"
    else
      flash.now[:alert] = "Invalid credentials!"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You are successfully logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :get_user, only: %i[edit update]

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path
    else
      flash.now[:alert] = @user.errors.full_messages.join(', ')
      render 'edit'
    end
  end

  private

  def get_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation, :email, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserRegistrationSystem</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id='nav'>
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <div class='nav-item'><%= link_to 'Log Out', logout_path %></div>
      <% else %>
        <div class='nav-item'><%= link_to 'Sign Up', signup_path %></div> |
        <div class='nav-item'><%= link_to 'Log In', login_path %></div> |
        <div class='nav-item'><%= link_to 'Forgot password', new_password_reset_path %></div>
      <% end %>
    </div>
    <p class='notice'><%= notice %></p>
    <p class='alert'><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Reset Password' %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot Password</h1>
<%= form_for @user, url: password_resets_path do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'Send Request' %>
  </div>
<% end %>

app/views/profiles/show.html.erb
<h1>Profile</h1>
<% if @user == current_user %>
  <%= button_to 'Edit', edit_user_path(@user), method: :get %>
<% end %>

<div class='profile-content'>
  <dl>
    <dt>username</dt>
    <dd><%= @user.username %></dd>

    <dt>email</dt>
    <dd><%= @user.email %></dd>

    <dt>password</dt>
    <dd><%= @user.password %></dd>
  </dl>
</div>

app/views/users/edit.html.erb
<h1>Update profile</h1>
<%= form_for @user do |f| %>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field(:password, value: @user.password) %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>